add_newline = true

format = """
$directory$git_branch$git_status
$character
"""

[directory]
style = "cyan"
truncation_length = 3
truncate_to_repo = true

[git_branch]
symbol = " "
style = "magenta"

[git_status]
style = "yellow"

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"

[python]
# Only show when these files exist in the current dir (or repo)
# detect_files = ["pyproject.toml", "requirements.txt", "Pipfile",
# "poetry.lock", ".python-version"]
# detect_extensions = ["py"]
# detect_folders = [".venv", "venv"]
